export const commandsList = {
  help: "🌟 Terminal Commands Menu 🌟\n\n🚀 Core Commands:\n- about: Discover the epic hackathon journey\n- register: Begin your adventure\n- prizes: Explore the treasure trove\n- judges: Meet the tech legends\n\n🎮 Fun Zone:\n- hack: Multi-level number challenge\n- surprise: Daily inspiration generator\n- theme: Customize your experience\n\n🌐 Community Hub:\n- participants: Real-time hacker count\n- tweets: Fresh community updates\n- sponsors: Meet our tech allies\n- faq: Unlock knowledge\n- clear: Reset your view\n\nPro tip: Try combining commands for hidden features! 🎯",
  about: "🚀 Welcome to the Future of Hacking! 🚀\n\n🌟 Bolt.new Hackathon 2024\n👥 Join 100,000+ Visionaries\n💰 $1M+ Prize Pool Awaits\n🌐 100% Virtual, 100% Revolutionary\n\n🎯 Our Mission:\nUnleash the next generation of tech innovation\nthrough collaborative coding excellence!\n\n🔥 Why Join?\n- Global networking opportunities\n- Cutting-edge tech challenges\n- Industry mentor access\n- Real-world impact\n\n🚀 Ready to make history? Type 'register' now!",
  prizes: "🏆 Epic Rewards Await! 🏆\n\n💫 Grand Champion: $500,000\n   🎯 Perks:\n   - 1:1 Mentorship with Tech Leaders\n   - Global Media Coverage\n   - Exclusive Investor Access\n\n🌟 Silver Innovator: $300,000\n   🎯 Perks:\n   - Startup Accelerator Fast-Track\n   - Cloud Credits Package\n   - Technical Resource Bundle\n\n✨ Bronze Visionary: $200,000\n   🎯 Perks:\n   - Industry Network Access\n   - Marketing Support Package\n   - Developer Tools Bundle\n\n🎁 Special Category Awards:\n- Most Innovative Use of AI\n- Best Social Impact\n- Community Choice\n\nEvery participant gets exclusive swag! 🎉",
  judges: "✨ Meet Your Tech Heroes ✨\n\n🏆 Panel of Legends:\n\n👨‍💻 @levelsio\n   • Serial Entrepreneur\n   • Built in Public Pioneer\n   • Bootstrapping Legend\n\n🚀 @OfficialLoganK\n   • Tech Visionary\n   • Community Builder\n   • Innovation Expert\n\n💡 @saranormous\n   • Product Genius\n   • Strategy Master\n   • Growth Hacker\n\n⚡ @theo\n   • Dev Advocate Extraordinaire\n   • Tech Educator\n   • Community Champion\n\n🔧 @youyuxi\n   • Framework Architect\n   • Open Source Leader\n   • Tech Innovator\n\n🌟 @thisiskp_\n   • Tech Influencer\n   • Industry Leader\n   • Vision Director\n\n💻 @alexalbert__\n   • Engineering Wizard\n   • System Architect\n   • Performance Guru\n\n🎯 @bentossell\n   • No-Code Revolutionary\n   • Startup Accelerator\n   • Community Builder\n\nStay tuned for live mentoring sessions! 🎓",
  sponsors: "🌟 Powered by Tech Giants 🌟\n\n⚡ Database Mastery\n   @Supabase - Where Data Dreams Come True\n\n🚀 Web Excellence\n   @Netlify - Deploy at Light Speed\n\n🌐 Edge Innovation\n   @CloudflareDev - Security Meets Performance\n\n🛡️ Quality Guardian\n   @GetSentry - Because Errors Don't Stand a Chance\n\n📈 Growth Champions\n   @Loops - Scaling Made Simple\n\n🔗 Blockchain Pioneer\n   @AlgoFoundation - Future of Finance\n\n🤖 AI Revolution\n   @ExaAILabs - Intelligence Amplified\n\n🏠 Community Hub\n   @hsrhackerhouse - Where Hackers Unite\n\nEach sponsor offers special perks! Type 'perks' to learn more 🎁",
  faq: "💡 Hack Smarter, Not Harder! 💡\n\n🤔 Common Questions:\n\n📅 When's the Big Day?\n   🎯 Coming Soon! Register now for early access\n\n👥 Who Can Join?\n   🎯 Everyone! From newbies to ninjas\n   🎯 Solo or team up (max 4 per team)\n\n🎮 What Can I Build?\n   🎯 Any tech innovation that excites you!\n   🎯 AI, Web3, Mobile, IoT - sky's the limit\n\n⚡ Quick Tips:\n- Register early for exclusive workshops\n- Join our Discord for team matching\n- Follow @Bolt_new for updates\n\n🎯 Pro Tip: Type 'register' to start your journey!\n",
  surprise: "🎲 Innovation Roulette 🎲\n\n   🌟 Your Daily Tech Challenge 🌟\n\n    ,------------------------,\n   /   BOLT.NEW INSPIRATION  \\\n  /                          \\\n |    [🎲 Roll for Ideas]    |\n |                           |\n |  Every Spin is a         |\n |  New Adventure!          |\n  \\                        /\n   \\    Type 'spin' to    /\n    \\     begin!         /\n     '------------------'\n\n🎯 Today's Theme:\nBuild something that makes\npeople smile! 😊\n\n💡 Bonus Challenge:\nAdd AI-powered features!\n\nType 'surprise' again for more inspiration!",
  theme: "🎨 Theme Wizard Activated! 🎨\n\nCurrent Theme: Cyber Neon\n\nAvailable Styles:\n1. Cyber Neon 🟣\n2. Retro Wave 🌅\n3. Matrix Green 🟢\n4. Ocean Deep 🌊\n5. Desert Gold 🏜️\n\nType 'theme <number>' to switch!\nExample: 'theme 2' for Retro Wave",
  hack: "🎮 Welcome to HACK MASTER 3000! 🎮\n\n🎯 Game Modes:\n- 'hack easy': 1-50 range, 5 hints\n- 'hack': 1-100 range, 3 hints\n- 'hack hard': 1-200 range, 2 hints\n\n💡 Commands:\n- Type a number to guess\n- 'hint': Get a clue about the target\n\n⚡ Features:\n- Adaptive difficulty levels\n- Smart hint system\n- Progress tracking\n\nReady? Choose your difficulty and start guessing!\n🎲 May the odds be in your favor! 🎲"
};